# Name: JC Ozor:

# Git Hub Repo: https://github.com/Berea-College-CSC-226/a03-master-sp23.git

# Google Doc Link: https://docs.google.com/document/d/12w-TnEIXpcMDXC3rTi1HhwzBr4eqWYmsQ2lTnQBnh0Y/edit?usp=sharing

import turtle

wn = turtle.Screen()
turtle.speed(5)
turtle.penup()
turtle.goto(-450, -200)
turtle.pendown()
turtle.title("House")
wn.colormode(255)
wn.bgcolor(179, 225, 172)
turtle.pensize(2)
turtle.pencolor("#947748")


def build():
    turtle.forward(900)
    turtle.backward(250)
    turtle.left(90)


def wall():
    turtle.color("#49524b")
    turtle.begin_fill()
    turtle.forward(200)
    turtle.left(90)
    turtle.forward(3)
    turtle.right(90)
    turtle.forward(5)
    turtle.left(90)
    turtle.forward(5)
    turtle.right(90)
    turtle.forward(5)
    turtle.left(90)
    turtle.forward(150)
    turtle.left(120)
    turtle.forward(25)
    turtle.right(120)
    turtle.forward(20)
    turtle.left(90)
    turtle.forward(187)
    turtle.end_fill()
    turtle.right(90)
    turtle.forward(175)


def pillar():
    turtle.speed(5)
    turtle.color("#1b211d")
    turtle.begin_fill()
    turtle.right(90)
    turtle.forward(187)
    turtle.left(90)
    turtle.forward(5)
    turtle.left(90)
    turtle.forward(187)
    turtle.end_fill()
    turtle.color("#49524b")
    turtle.left(90)
    turtle.forward(173)
    turtle.color("#1b211d")
    turtle.begin_fill()
    turtle.left(90)
    turtle.forward(187)
    turtle.right(90)
    turtle.forward(5)
    turtle.right(90)
    turtle.forward(187)
    turtle.end_fill()
    turtle.backward(187)
    turtle.right(90)
    turtle.forward(2)
    turtle.forward(180)


def wall2():
    turtle.speed(5)
    turtle.color("#49524b")
    turtle.begin_fill()
    turtle.forward(192)
    turtle.left(90)
    turtle.forward(187)
    turtle.left(90)
    turtle.forward(193)
    turtle.end_fill()
    turtle.left(90)
    turtle.forward(187)


def pillar2():
    turtle.speed(5)
    turtle.color("#1b211d")
    turtle.begin_fill()
    turtle.left(90)
    turtle.forward(195)
    turtle.left(90)
    turtle.forward(187)
    turtle.right(90)
    turtle.forward(7)
    turtle.right(90)
    turtle.forward(187)
    turtle.left(90)
    turtle.forward(3)
    turtle.right(90)
    turtle.forward(5)
    turtle.left(90)
    turtle.forward(3)
    turtle.right(90)
    turtle.forward(7)
    turtle.right(90)
    turtle.forward(188)
    turtle.right(135)
    turtle.forward(16)
    turtle.end_fill()
    turtle.right(225)


def roof():
    turtle.speed(5)
    turtle.color("#b84221")
    turtle.begin_fill()
    turtle.right(-45)
    turtle.forward(180)
    turtle.right(94)
    turtle.forward(170)
    turtle.right(131)
    turtle.forward(240)
    turtle.end_fill()
    turtle.speed(5)
    turtle.begin_fill()
    turtle.right(-225)
    turtle.forward(330)
    turtle.right(94)
    turtle.forward(285)
    turtle.right(131)
    turtle.forward(300)
    turtle.end_fill()
    turtle.speed(5)
    turtle.left(90)
    turtle.forward(10)
    turtle.right(90)
    turtle.forward(310)
    turtle.begin_fill()
    turtle.right(-225)
    turtle.forward(130)
    turtle.right(45)
    turtle.forward(200)
    turtle.right(-225)
    turtle.forward(130)
    turtle.end_fill()


def trims():
    turtle.speed(5)
    turtle.color("#18191f")
    turtle.right(45)
    turtle.forward(200)
    turtle.right(-225)
    turtle.forward(130)
    turtle.right(45)
    turtle.forward(195)
    turtle.right(-45)
    turtle.forward(190)
    turtle.right(94)
    turtle.forward(287)
    turtle.right(-229)
    turtle.forward(195)
    turtle.right(225)
    turtle.forward(28)
    turtle.right(-225)
    turtle.forward(250)
    turtle.right(135)
    turtle.forward(180)
    turtle.right(91)
    turtle.forward(170)
    turtle.right(134)
    turtle.forward(240)


def wind():
    turtle.speed(5)
    turtle.penup()
    turtle.left(90)
    turtle.forward(50)
    turtle.pendown()
    turtle.color("#91bfbe")
    turtle.begin_fill()
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(130)
    turtle.right(90)
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(130)
    turtle.end_fill()


def frame():
    turtle.speed(10)
    turtle.color("#38393d")
    turtle.right(90)
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(130)
    turtle.right(90)
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(130)
    turtle.right(90)
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(65)
    turtle.right(90)
    turtle.forward(55)
    turtle.right(90)
    turtle.forward(65)
    turtle.right(90)
    turtle.forward(27.5)
    turtle.right(90)
    turtle.forward(130)


def door():
    turtle.color("#473728")
    turtle.penup()
    turtle.left(90)
    turtle.forward(115)
    turtle.left(90)
    turtle.forward(225)
    turtle.pendown()
    turtle.begin_fill()
    turtle.left(90)
    turtle.forward(135)
    turtle.right(90)
    turtle.forward(65)
    turtle.right(90)
    turtle.forward(135)
    turtle.end_fill()


def wind2():
    turtle.penup()
    turtle.left(90)
    turtle.forward(95)
    turtle.left(90)
    turtle.forward(100)
    turtle.pendown()
    turtle.color("#91bfbe")
    turtle.begin_fill()
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(95)
    turtle.end_fill()


def frame2():
    turtle.color("#38393d")
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(90)
    turtle.forward(50)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(90)
    turtle.forward(25)
    turtle.right(90)
    turtle.forward(47.5)
    turtle.right(90)
    turtle.forward(50)
    turtle.hideturtle()


def main():
    build()
    wall()
    pillar()
    wall2()
    pillar2()
    roof()
    trims()
    wind()
    frame()
    door()
    wind2()
    frame2()


main()

wn.exitonclick()
